### ISSUE TITLE
Can the algorithm process any single-channel signals?

### ISSUE THREAD

**Issue by NewEricWang** [nuniz/blind_rt60#1]
Great work! I use the script to estimate RT60 of my audio, but I find the estimated value is larger than real value. I use a single-channel audio. 
If I want to estimate RT20, which parameters should be changed?

**Comment by nuniz** [comment]
Thanks :-)

If the estimated time is larger than expected you can modify the algorithm parameters to better fit your problem. I've written about the parameters and the strategy for estimating the correct decay time at the README.md file. 

To calculate the RTx you can use the following formula:
e^(-RTx/ tau) = 10^(-x/20)
RTx = - x/20 * 1/log10(e^-1)

For x=20dB, the solution is quite simple
RT20 = tau

Tau is an attribute in BlindRT60, and is calculated during the estimation. 

I might another function to calculate the RTx using tau if that's interesting.

**Comment by nuniz** [comment]
Thanks :-)

If the estimated time is larger than expected you can modify the algorithm parameters to better fit your problem. I've written about the parameters and the strategy for estimating the correct decay time at the README.md file.

To calculate the RTx you can use the following formula:
e^(-RTx/ tau) = 10^(-x/20)
RTx = - x * tau /20 * 1/log10(e^-1)

Tau is an attribute of BlindRT60, and is calculated during the estimation.

I might add another function to calculate the RTx using tau if that's interesting.

**Comment by NewEricWang** [comment]
Thanks!  I see. Thank you for your guidance.
I don't really understand what the effect of parameter "percentile" is. 
I find that the estimated rt60 is more accurate if I set up  a smaller value for  parameter "percentile".
For my input audio, when seting "percentile" as 15 the estimated rt60 is More reasonable.

**Comment by nuniz** [comment]
The percentile calculation assumes that tau follows a left-tail distribution that is unimodal and symmetric, and that the percentile will track the peak value. If calibration works, great; if not, examine the plots for assumption breaks. Use the visualization plot to check for deviations caused by outliers, connected speech, or multimodal distributions.
